kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/tosin2013/responsible-ai-ml-pipeline.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: tutorial-bias-advertising
  namespace: tutorial-bias-advertising
  labels:
    app: tutorial-bias-advertising
    app.kubernetes.io/component: tutorial-bias-advertising
    app.kubernetes.io/instance: tutorial-bias-advertising
    app.kubernetes.io/name: tutorial-bias-advertising
    app.kubernetes.io/part-of: tutorial-bias-advertising
spec:
  lookupPolicy:
    local: false

