apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: tutorial-bias-advertising
  namespace: tutorial-bias-advertising
spec:
  source:
    git:
      ref: main
      uri: 'https://github.com/tosin2013/responsible-ai-ml-pipeline.git'
    type: Git
    contextDir: applications/tutorial_bias_advertising
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
