kind: Build
apiVersion: build.openshift.io/v1
metadata:
  name: tutorial-bias-advertising-1
  labels:
    app: tutorial-bias-advertising
    app.kubernetes.io/component: tutorial-bias-advertising
    app.kubernetes.io/instance: tutorial-bias-advertising
    app.kubernetes.io/name: tutorial-bias-advertising
    app.kubernetes.io/part-of: tutorial-bias-advertising
    buildconfig: tutorial-bias-advertising
    openshift.io/build-config.name: tutorial-bias-advertising
    openshift.io/build.start-policy: Serial
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'tutorial-bias-advertising:latest'
    pushSecret:
      name: builder-dockercfg-vlbbw
  resources: {}
  triggeredBy:
    - message: Build configuration change
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'https://github.com/tosin2013/responsible-ai-ml-pipeline.git'
    contextDir: applications/tutorial_bias_advertising
